# Generated by Django 4.2.16 on 2024-11-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StrengthRatio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.CharField(choices=[('chest', 'Chest'), ('back', 'Back'), ('shoulders', 'Shoulders'), ('biceps', 'Biceps'), ('triceps', 'Triceps'), ('legs_squat', 'Legs (Squat)'), ('legs_deadlift', 'Legs (Deadlift)')], max_length=20)),
                ('ratio', models.FloatField()),
                ('equipment_type', models.CharField(choices=[('barbell', 'Barbell'), ('dumbbell', 'Dumbbell')], default='barbell', max_length=20)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True)),
                ('min_age', models.IntegerField(blank=True, null=True)),
                ('max_age', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
